import { contextFindInput, contextInspectInput, memoryInput, planInput } from "./schemas.js";
import type { ToolRuntime } from "./runtime.js";

export const PUBLIC_TOOL_NAMES = ["context.find", "context.inspect", "memory", "plan"] as const;
type Register = (name: string, description: string, schema: any, handler: (input: any) => Promise<unknown>) => void;

export function registerPublicTools(register: Register, runtime: ToolRuntime): void {
  register("context.find", "Find a small ranked set of local refs. Use this before inspect; results declare the views each ref supports and retrieval diagnostics.", contextFindInput, (value) => runtime.contextFind(value));
  register("context.inspect", "Inspect one ref returned by context.find. Reuse the ref exactly and select only one of its available_views.", contextInspectInput, (value) => runtime.contextInspect(value));
  register("memory", `READ current: {"action":"current"} reads active spec, records, and state. For continuation use section, offset, state_token, and item_id ONLY with current. Every action uses the operator-selected active memory; never send memory_id or workspace. WRITE spec_set: {"action":"spec_set","summary":"Goal","requirements":[{"statement":"Observable condition","kind":"constraint","priority":"must"}]}. spec_set replaces the complete desired spec; it NEVER reads records and requires both summary and the complete requirements list. Each requirement needs statement, kind (behavior or constraint), and lowercase priority (must or should). Omit id for a new requirement; reuse only an existing server-issued R* ID when updating.
WRITE note: {"action":"note","type":"evidence","text":"Observed behavior","evidence_refs":["<inspected context ref>"]} saves a durable finding, not tool-call bookkeeping. WRITE resolve: {"action":"resolve","record_id":"M1","status":"confirmed","reason":"Inspected source"} updates a memory record. M* record IDs are NOT context evidence refs. evidence_refs must come from context.find and be inspected with context.inspect in this memory. Follow server-owned stage, required_skill, and next_action.`, memoryInput, (value) => runtime.memory(value));
  register("plan", `Persistent plan for the active structured spec. Actions: current, create, complete_current, revise_current. Create: {"action":"create","steps":[{"title":"Implement feature","objective":"Add the required behavior","writes":["src/feature.ts"]}]}. Omit writes for a read-only step. Paths may be relative or absolute inside the active repository. The server assigns IDs, derives kind, and runs configured checks. Do not supply coverage, test steps, repository IDs, or verification commands. Revise only the current step with {"action":"revise_current","reason":"...","step":{"title":"...","objective":"...","writes":["src/feature.ts"]}}. Call current before mutation, then complete_current when ready. Final review remains operator-gated.`, planInput, (value) => runtime.plan(value));
}
